# This file is used to store secrets and configuration for your CircuitPython board.
# Fill in your WiFi and MQTT credentials below.

CIRCUITPY_WIFI_SSID = "YOUR_WIFI_SSID"
CIRCUITPY_WIFI_PASSWORD = "YOUR_WIFI_PASSWORD"

MQTT_BROKER = "coventry.paddez.com"
MQTT_PORT = 1883
MQTT_TOPIC = "sensors/rfid/reads"
MQTT_USERNAME = "Paddez"
MQTT_PASSWORD = "test123"

# Optional: Define your UART pins if not using defaults
# For example, for an ESP32-S2:
# RFID_RX_PIN = "IO44" # Example, adjust to your board's RX pin
# RFID_TX_PIN = "IO43" # Example, adjust to your board's TX pin (often not needed for reader-only)
